package abeshtemplate

import "text/template"

var ServiceTemplate = template.Must(template.New("service").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package {{.PackageName}}

import (
	"context"
	"github.com/mkawserm/abesh/constant"
	"github.com/mkawserm/abesh/iface"
	"github.com/mkawserm/abesh/model"
	"github.com/mkawserm/abesh/registry"
)

type {{.InterfaceName}} struct {
	
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) Name() string {
	return "{{.ServiceName}}"
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) Version() string {
	return "0.0.1"
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) Category() string {
	return string(constant.CategoryService)
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) ContractId() string {
	return "{{.ContractID}}"
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) GetConfigMap() iface.ConfigMap {
	panic("implement me")
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) Setup() error {
	panic("implement me")
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) SetConfigMap(values iface.ConfigMap) error {
	panic("implement me")
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) New() iface.ICapability {
	return &{{.InterfaceName}}{}
}

func ({{.InterfaceRune}} *{{.InterfaceName}}) Serve(ctx context.Context, cap iface.ICapabilityRegistry, input *model.Event) (*model.Event, error) {
	panic("implement me")
}

func init() {
	registry.GlobalRegistry().AddCapability(&{{.InterfaceName}}{})
}
`))

